### ISSUE TITLE
Socket deletion on `terminate`

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/cl-electron#15]
## Question 1

The call to `uiop:terminate-process` in `terminate` deletes both sockets since it kills the process. Do we really need `(uiop:delete-file-if-exists (lisp-socket-path interface))` in `terminate`? Or, in other words, could it happen that there would be no Electron `process` but `lisp.socket` exists?

## Question 2

I've noticed that the following sometimes results in the error below, which means that the creation of the window is happening before `launch` had time to create the socket. 

```lisp
(progn
  (setf electron::*interface*
        (make-instance
         'electron:interface
         :electron-socket-path (uiop:xdg-runtime-dir "electron.socket")
         :lisp-socket-path (uiop:xdg-runtime-dir "lisp.socket"))) 
  (electron:launch)
  ;; (sleep 1)
  (defvar win (make-instance 'electron:browser-window)))
```

```lisp
#<Syscall "connect" signalled error ENOENT(2) "No such file or directory" FD=10>
   [Condition of type IOLIB/SYSCALLS:ENOENT]

Restarts:
 0: [RETRY] Retry SLY mREPL evaluation request.
 1: [*ABORT] Return to SLY's top level.
 2: [ABORT] abort thread (#<THREAD tid=17882 "sly-channel-1-mrepl-remote-1" RUNNING {1008901AB3}>)

Backtrace:
 0: ((LAMBDA NIL :IN IOLIB/SOCKETS:CONNECT))
      [No Locals]
 1: (IOLIB/SOCKETS::CALL-WITH-SOCKET-TO-WAIT-CONNECT #<active local stream socket, unconnected {100D3F62C3}> #<FUNCTION (LAMBDA NIL :IN IOLIB/SOCKETS:CONNECT) {100D57525B}> T)
      Locals:
        SOCKET = #<active local stream socket, unconnected {100D3F62C3}>
        THUNK = #<FUNCTION (LAMBDA () :IN IOLIB/SOCKETS:CONNECT) {100D57525B}>
        TIMEOUT = NIL
        WAIT = T
 2: ((:METHOD IOLIB/SOCKETS:CONNECT (IOLIB/SOCKETS:LOCAL-SOCKET IOLIB/SOCKETS:LOCAL-ADDRESS)) #<active local stream socket, unconnected {100D3F62C3}> #<Unix socket address: "/run/user/1000/electron.socket..
      Locals:
        IOLIB/SOCKETS:ADDRESS = #<Unix socket address: "/run/user/1000/electron.socket">
        IOLIB/SOCKETS:SOCKET = #<active local stream socket, unconnected {100D3F62C3}>
        IOLIB/SOCKETS::WAIT = T
 3: (IOLIB/SOCKETS::%%INIT-SOCKET/LOCAL-STREAM-ACTIVE #<active local stream socket, unconnected {100D3F62C3}> NIL "/run/user/1000/electron.socket")
      Locals:
        LOCAL-FILENAME = NIL
        REMOTE-FILENAME = "/run/user/1000/electron.socket"
        SOCKET = #<active local stream socket, unconnected {100D3F62C3}>
 4: (SEND-MESSAGE #<BROWSER-WINDOW {100D3F1B03}> "ID573 = new BrowserWindow();")
      Locals:
        MESSAGE = "ID573 = new BrowserWindow();"
        IOLIB/SOCKETS:SOCKET = #<active local stream socket, unconnected {100D3F62C3}>
        TARGET = #<BROWSER-WINDOW {100D3F1B03}>
 5: ((:METHOD INITIALIZE-INSTANCE :AFTER (BROWSER-WINDOW)) #<BROWSER-WINDOW {100D3F1B03}> :OPTIONS "") [fast-method]
      Locals:
        BROWSER-WINDOW = #<BROWSER-WINDOW {100D3F1B03}>
        SB-FORMAT::FORMAT-ARG2 = ""
 6: ((SB-PCL::EMF INITIALIZE-INSTANCE) #<unused argument> #<unused argument> #<BROWSER-WINDOW {100D3F1B03}>)
 7: ((:METHOD MAKE-INSTANCE (CLASS)) #<STANDARD-CLASS ELECTRON:BROWSER-WINDOW>) [fast-method]
...
```

------

CC @Ambrevar @jmercouris 

(@jmercouris I've deleted your first reply since I've edited my top post heavily.)

**Comment by jmercouris** [comment]
Yes, probably.

**Comment by jmercouris** [comment]
Depends, is it part of the contract in the API that upon termination of a process the sockets will be deleted? If it is, then we don't, otherwise we do.

**Comment by Ambrevar** [comment]
It has nothing to do with Posix / Linux: socket must be removed by the process.
We do this with iolib's `iolib:with-open-socket`.

The `uiop:delete-file-if-exists (lisp-socket-path interface))` is technically not necessary, but it does not hurt as a safe-guard in case we forget to handle errors properly in the body.

As for question 2, this is an issue indeed, we should have a mean to wait for the server to be ready.
Off the top of my head, I'd say that electron should write a special message to the Lisp socket or something like that.
It should be part of our API / contract that this message is consumed.

**Comment by Ambrevar** [comment]
> Are you sure? When I send the KILL signal to the Electron process (from Emacs' proced), the sockets are deleted. IOlib isn't involved in it.

Are you sure back? :)
I just tried this:

```sh
kill -9 4775
```

(PID of the SBCL image) and the sockets were _not_ cleaned up.

**Comment by Ambrevar** [comment]
Oh yes, of course this works since the Lisp side handles killed Electron processes, but what I meant is that's only one side of the issue of "cleaning up sockets".

Anyways, I believe the answer to Question 1 is still as was said before:


> The `uiop:delete-file-if-exists (lisp-socket-path interface))` is technically not necessary, but it does not hurt as a safe-guard in case we forget to handle errors properly in the body.

**Comment by aadcg** [comment]
Commit 98fc836 puts an end to question 1.

Commit e647943dac358f97f3a27ab4a49dad3625c5c471 should have fixed question 2.

**Comment by aadcg** [comment]
> Commit [98fc836](https://github.com/atlas-engineer/cl-electron/commit/98fc8362210ad081c5fa116d3929f83a2562f2f5) puts an end to question 1.

This is incorrect.
