### ISSUE TITLE
Properly handle the initialization of windows

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/cl-electron#16]
Instead of relying on [this workaround](https://github.com/atlas-engineer/cl-electron/blob/master/source/browser-window.lisp#L14), which has [serious consequences](https://github.com/electron/electron/issues/39281), I suggest checking whether `app.isReady()` returns `true`.

From the docs:

> [BrowserWindow] This module cannot be used until the ready event of the app module is emitted.

[More info about the ready app event](https://www.electronjs.org/docs/latest/api/app#event-ready).

-----

@jmercouris I'm just wondering: (1) were you unaware of this or (2) did you assume that the app would be ready?

**Comment by jmercouris** [comment]
I think you can wait indefinitely and it will never emit the "ready" signal. That is what I experienced on Qt. Not sure if it is different here. If you think this signal will work, perhaps it is the way.

**Comment by jmercouris** [comment]
I mean when in the past I was using QtWebEngine

**Comment by jmercouris** [comment]
OK then :-)

**Comment by jmercouris** [comment]
Well, I've waited, and waited... and I've never seen this signal emitted. If we add a "isReady" listener, will it magically start being emitted? This by the way has led to bugs of javascript not being evaluated in the message buffer.

**Comment by jmercouris** [comment]
Except... it is! You shall see later today.

**Comment by jmercouris** [comment]
I DON'T BELIEVE I CANNOT BELIEVE
