### ISSUE TITLE
Spawning a new window after killing all others

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/cl-electron#3]
Steps to reproduce:

```lisp
> (launch)
> (defparameter window (make-instance 'browser-window))
> (kill window)
> (defparameter window (make-instance 'browser-window))

Couldn't write to #<SB-SYS:FD-STREAM for "socket 127.0.0.1:52720, peer: 127.0.0.1:3000" {100C80BEA3}>:
  Broken pipe
   [Condition of type SB-INT:BROKEN-PIPE]

```
[After reading this explanation](https://unix.stackexchange.com/a/84828), it seems to me that our IPC mechanism to talk to Electron needs to be re-designed.

**Comment by Ambrevar** [comment]
Fixed with 792754de0ba75d4bff2ad9a0b15c28f3945d4510.

**Comment by jmercouris** [comment]
Classic pebkac ;-)

**Comment by Ambrevar** [comment]
> Long story short: this is a non-problem. It wasn't solved in the sense that everything's working as it should be. As always, the issue is between the keyboard and the chair.

I'm confused, is there a problem?  Even a pebkac?

You seem to imply that making a window without a running instance could be expected to work nonetheless (e.g. by starting an instance automatically).  Is that what you mean?

**Comment by Ambrevar** [comment]
OK!
