### ISSUE TITLE
`BrowserView`s expected to be deprecated on Electron 30

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/cl-electron#32]
Initially [planned for version 29](https://github.com/electron/electron/pull/40759), it has been [postponed for 30](https://github.com/electron/electron/pull/41060).

This library relies heavy on this API, which will become [EOL by the end of August 2024](https://www.electronjs.org/docs/latest/tutorial/electron-timelines).

**Comment by NoahAndrews** [comment]
Note that `BrowserView` will be replaced by the new `WebContentsView` API, and as I understand it there's even a shim so that you don't have to port your code if you don't want to.

**Comment by aadcg** [comment]
Closed via 801d11b.
