### ISSUE TITLE
Document about compatible electron versions

### ISSUE THREAD

**Issue by glyh** [atlas-engineer/cl-electron#33]
I just tested out nyxt-electron and it crashes. I'm wondering is there any information on which electron should I use? Cause I'm on v29.1.5

**Comment by jmercouris** [comment]
Thanks @glyh , it should work with the latest electron version. We are currently testing with version 29.X.Y. Are you unable to run any of the demos? Are you on Windows perchance? We have only tested on macOS/Linux.

**Comment by glyh** [comment]
https://github.com/atlas-engineer/nyxt/issues/3364, I'll try to see if I can run demos here.

**Comment by aadcg** [comment]
We're targeting version 29 as of today. See 93e0b11.
