### ISSUE TITLE
Interplay between fn `create-socket-path` and slot `socket-directory`

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/cl-electron#36]
Commit 57dba90fd4478e2021f04996affc5c03a27e7586 introduced slot `socket-directory` but didn't use it anywhere.

The logic behind the path is repeated in the slot and function. The latter should be turned into a method.

Noted while working on #35.

**Comment by jmercouris** [comment]
The socket-directory is used when creating tmp sockets for callbacks etc. If you run the protocol demo, or the window handler demo you'll note the `cl-electron` dir will be populated with sockets.
