### ISSUE TITLE
Slow synchronous socket communication

### ISSUE THREAD

**Issue by jmercouris** [atlas-engineer/cl-electron#37]
The current method for doing synchronous socket communication is rather slow.

To remedy this we can use a C extension for Node.js to do synchronous socket reads rather than our sync-socket method.

**Comment by aadcg** [comment]
After some thought, I considered the two possibilities: (1) always sending `event.preventDefault()` and (2) the approach proposed above.

Both require hacks. The former requires faking input events and the latter complicates the build process greatly. 

As of today, and given the information I have, I'd lean on (1).

**Comment by jmercouris** [comment]
Even if we do simulate fake input events, the input will still be unbearably slow, so I think we should very carefully consider. It is easier to make a build process robust than to improve the speed of a socket.

**Comment by aadcg** [comment]
Closed by #43.
