### ISSUE TITLE
Use local Unix socket instead of BSD socket

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/cl-electron#4]
We BSD is vulnerable (and possibly slower) than Unix socket.

1. On the Lisp side, simply replace usocket with iolib.
2. Can Electron create Unix sockets?
  As far as I understand, it's enough to replace the port by a path:
  https://nodejs.org/api/net.html

**Comment by aartaka** [comment]
Node js is capable of anything (I guess making coffee too 😨)

**Comment by aadcg** [comment]
No longer true since https://github.com/usocket/usocket/commit/7a24c571541b1d046976f0c175f1f2658dbdf0f7.
