### ISSUE TITLE
Remove `cl-` prefix from package name

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/cl-electron#5]
While it's customary to prefix _systems_ with `cl-`, not so much for packages, since it's pretty clear we are dealing with CL at this point.

The few existing packages that prefix themselves with `cl-` are indeed annoying :)

Then we can remove the package nickname.

**Comment by jmercouris** [comment]
Complete with: c1a2bd3

**Comment by Ambrevar** [comment]
Thanks!

I don't think it's necessary to retain the nickname.  I don't see the use, plus there is no widespread practice of doing it.
