### ISSUE TITLE
Why not use Parenscript?

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/cl-electron#8]
Since these bindings are going to be mostly JavaScript, why not use Parenscript?
It's in the .asd deps but does not seem to be used.

@jmercouris ?

**Comment by aartaka** [comment]
The last motivation I've heard from John is that it was initially easier to use raw strings 🙃

**Comment by jmercouris** [comment]
Indeed, eventually it'll be in parenscript!

**Comment by aadcg** [comment]
Parenscript would introduce another layer of indirection, but the logic is already quite complex due to the need of `%quote-js`.
